version: "3"

services:
  vscode-server:
    container_name: vscode-server
    #build: ./vscode-server
    image: sinredempti0n/vscode-server:4.22.0
    restart: always
    ports:
      - 443:8080
    volumes:
      - ./vscode-server/local:/home/sinredempti0n/.local
      - ./vscode-server/config:/home/sinredempti0n/.config
      - ./project:/home/sinredempti0n/project
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  
  langchain-clickhouse-server:
    container_name: langchain-clickhouse-server
    image: clickhouse/clickhouse-server:23.5.2.7
    ports:
      - 8123:8123
      - 9000:9000
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
