version: "3"

services:
  vscode-server:
    container_name: vscode-server
    #build: ./vscode-server
    image: sinredempti0n/vscode-server:4.22.0
    restart: always
    ports:
      - 443:8080
    volumes:
      - ./vscode-server/local:/home/sinredempti0n/.local
      - ./vscode-server/config:/home/sinredempti0n/.config
      - ./project:/home/sinredempti0n/project